### ISSUE TITLE
There is a link that doesn't work on Getting Started page

### ISSUE THREAD

**Issue by pescamillam** [arquillian/arquillian.github.com#357]
##### Issue Overview

There is a link that doesn't work as expected on http://arquillian.org/guides/getting_started/ 

##### Expected Behaviour

When you click on "Open the Project in Eclipse" link you should be taken to the title "Open the Project in Eclipse"

##### Current Behaviour

When you click on "Open the Project in Eclipse" link it doesn't do anything

##### Steps To Reproduce
1. Go to http://arquillian.org/guides/getting_started/
2. Search for "Open the Project in Eclipse" link
3. Click on it

##### Additional Information

Problem fixed in pull request: https://github.com/arquillian/arquillian.github.com/pull/356

**Comment by bartoszmajsak** [comment]
Turned out to be a bigger issue than just a missing anchor. Those links were autogenerated by the custom transformer based on the text in the heading. As we updated Awestruct we lost this functionality (or at least we were trying to register the transformer not the right way anymore).

It has been fixed with @587710e4acd5d2577775d712c45912346821d8d4

Thanks again for reporting and looking forward to more contributions!
